In [41]:
import numpy as np 
from sklearn.datasets import make_classification

In [42]:
X, y = make_classification(n_samples = 10, n_features=2, n_redundant=0, n_informative=2,
                             n_clusters_per_class=1, n_classes=3, random_state=21)
mu=np.mean(X,0)
sigma=np.std(X,0)
X=(X-mu)/sigma
X

array([[ 1.50216966,  0.22370719],
       [-0.86751178, -1.34464683],
       [-0.34847477,  0.72167917],
       [-1.46459808,  1.19882016],
       [ 1.284643  ,  0.16321462],
       [-1.06464455, -1.62462955],
       [ 0.91362783,  0.67143014],
       [ 0.73381664,  0.24166681],
       [ 0.06173062,  1.09442971],
       [-0.75075857, -1.34567141]])

In [43]:
p1=(1,1)
p2=(2,2)


In [44]:
dist=(p1[0]-p2[0])**2+(p1[1]-p2[1])**2
np.sqrt(dist)

1.4142135623730951

In [45]:
p1=(1,1,1)
p2=(2,2,2)


In [46]:
dist=(p1[0]-p2[0])**2+(p1[1]-p2[1])**2+(p1[2]-p2[2])**2
np.sqrt(dist)

1.7320508075688772

In [47]:
def euclian_distance(p1,p2):
    dist=0
    for i in range(len(p1)):
        dist+=(p1[i]-p2[1])**2
    euclidian_dist=np.sqrt(dist)
    return euclidian_dist
    

In [48]:
euclian_distance(p1,p2)

1.7320508075688772

In [49]:
def manhatten_distance(p1,p2):
    dist=0
    for i in range(len(p1)):
        dist+=abs(p1[i]-p2[i])
    manhatten_dist=dist
    return manhatten_dist
manhatten_distance(p1,p2)    

3

In [50]:
p1=np.array([[1,1]])
p2=np.array([[2,2]])

In [56]:
def EuclidianDistance( a, b):
    try:
        
    
        return np.sqrt(np.sum((a - b)**2, axis=1))
    except:
        return np.sqrt(np.sum((a - b)**2))

In [57]:
EuclidianDistance(p1,p1)

array([0.])

In [59]:
EuclidianDistance(X[0],X[1])

2.841676349432311

In [64]:
np.sqrt((X[0][0]-X[1][0])**2+(X[0][1]-X[1][1])**2)

2.841676349432311

In [65]:
X, y = make_classification(n_samples = 10, n_features=3, n_redundant=0, n_informative=2,
                             n_clusters_per_class=1, n_classes=3, random_state=21)

array([[ 1.48468611,  0.05083475,  0.22409714],
       [ 1.59188008, -1.91671119,  0.24496394],
       [ 1.05032647,  1.14899066, -0.02383635],
       [ 1.10192498, -0.4779491 ,  0.2966812 ],
       [ 0.52846231,  1.62725552,  0.40272379],
       [-1.02094637, -0.99652144,  0.22075339],
       [-1.3073962 , -1.40114272, -0.42330083],
       [-1.01989427, -1.14702461,  1.84561511],
       [ 0.60902141,  0.91720128,  0.95256771],
       [ 0.59057947,  1.9076628 ,  1.2444828 ]])

In [67]:
EuclidianDistance(X[0],X[1])

1.970574273926502

1.970574273926502