In [25]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import tensorflow as tf 

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import time
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense


In [26]:
data=pd.read_csv('IRIS.csv')
#Y=data.pop('species')
species=dict(zip(list(data['species'].unique()), ([0, 1, 2])))

data['species'].replace(species,inplace=True)
Y=data.pop('species')
X=data.values
y_dummy=pd.get_dummies(Y)


In [27]:
X_train,X_test,y_train,y_test=train_test_split(X,y_dummy)


In [28]:
inputs=tf.keras.Input(shape=X.shape[1])
layer1=tf.keras.layers.Dense(32,activation='relu')(inputs)
layer2=tf.keras.layers.Dense(64,activation='relu')(layer1)
layer3=tf.keras.layers.Dense(64,activation='relu')(layer2)
outputs=tf.keras.layers.Dense(3,activation='softmax')(layer3)
model=tf.keras.Model(inputs=inputs,outputs=outputs)
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['acc'])

In [29]:
model.summary()

Model: "model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_3 (InputLayer)        [(None, 4)]               0         
                                                                 
 dense_8 (Dense)             (None, 32)                160       
                                                                 
 dense_9 (Dense)             (None, 64)                2112      
                                                                 
 dense_10 (Dense)            (None, 64)                4160      
                                                                 
 dense_11 (Dense)            (None, 3)                 195       
                                                                 
Total params: 6,627
Trainable params: 6,627
Non-trainable params: 0
_________________________________________________________________


In [30]:
model.fit(X,y_dummy,epochs=100,validation_data=(X_test,y_test))

Epoch 1/100
5/5 [==============================] - 2s 92ms/step - loss: 0.7129 - acc: 0.1000 - val_loss: 0.6582 - val_acc: 0.3158
Epoch 2/100
5/5 [==============================] - 0s 17ms/step - loss: 0.6420 - acc: 0.3333 - val_loss: 0.6199 - val_acc: 0.3158
Epoch 3/100
5/5 [==============================] - 0s 18ms/step - loss: 0.6059 - acc: 0.3333 - val_loss: 0.5940 - val_acc: 0.3158
Epoch 4/100
5/5 [==============================] - 0s 18ms/step - loss: 0.5789 - acc: 0.3600 - val_loss: 0.5707 - val_acc: 0.5000
Epoch 5/100
5/5 [==============================] - 0s 18ms/step - loss: 0.5567 - acc: 0.6533 - val_loss: 0.5454 - val_acc: 0.6842
Epoch 6/100
5/5 [==============================] - 0s 17ms/step - loss: 0.5324 - acc: 0.6667 - val_loss: 0.5178 - val_acc: 0.6842
Epoch 7/100
5/5 [==============================] - 0s 20ms/step - loss: 0.5044 - acc: 0.6667 - val_loss: 0.4892 - val_acc: 0.6842
Epoch 8/100
5/5 [==============================] - 0s 20ms/step - loss: 0.4749 - acc: 0.66

In [31]:
tf.argmax(model.predict(X_test),axis=1)

2/2 [==============================] - 0s 4ms/step


<tf.Tensor: shape=(38,), dtype=int64, numpy=
array([2, 2, 0, 0, 1, 1, 1, 2, 0, 0, 2, 1, 1, 2, 1, 1, 0, 2, 0, 2, 0, 1,
       0, 2, 0, 0, 0, 1, 0, 0, 2, 0, 2, 1, 2, 2, 1, 2])>

In [32]:
tf.argmax(y_test,axis=1)

<tf.Tensor: shape=(38,), dtype=int64, numpy=
array([2, 2, 0, 0, 1, 1, 1, 1, 0, 0, 2, 1, 1, 2, 1, 1, 0, 2, 0, 2, 0, 1,
       0, 2, 0, 0, 0, 1, 0, 0, 2, 0, 2, 1, 2, 2, 1, 2])>